### ISSUE TITLE
Update podspec GetStreamActivityFeed to 2.2.2

### ISSUE THREAD

**Issue by AndrewRudyk** [GetStream/swift-activity-feed#10]
Could you please update podspec to GetStreamActivityFeed (~> 2.2.2), as old versions  (2.2.1 and lower) of GetStreamActivityFeed pull old dependencies (for example, Alamofire version 4).

pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 5.2.0, ~> 5.2)

  In Podfile:
    Alamofire (~> 5.1)

    GetStreamActivityFeed (~> 2.2) was resolved to 2.2.1, which depends on
      GetStream (~> 2.2) was resolved to 2.2.0, which depends on
        GetStream/Core (= 2.2.0) was resolved to 2.2.0, which depends on
          Moya (~> 13.0) was resolved to 13.0.0, which depends on
            Moya/Core (= 13.0.0) was resolved to 13.0.0, which depends on
              Alamofire (~> 4.1)

**Comment by b-onc** [comment]
@AndrewRudyk The issue is in GetStream pod, not GetStreamActivityFeed.
There's an open issue in that repo: GetStream/stream-swift#25
And an open PR which should resolve this problem too: GetStream/stream-swift#28
We will be releasing the new version soon.
