### ISSUE TITLE
Could not load PostHeaderTableViewCell

### ISSUE THREAD

**Issue by marcnpopa** [GetStream/swift-activity-feed#14]
Hi, I'm playing with the iOS Activity Feed tutorial (https://getstream.io/ios-activity-feed/tutorial/) and all works well until I try to add an item to the feed and I get:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle<...> with name 'PostHeaderTableViewCell''
*I used Swift Package Manager to integrate your library
A solution/fix would be greatly appreciated, thank you.

**Comment by b-onc** [comment]
Hello @marcnpopa 
SPM support for Activity Feeds is not implemented yet, so it's not usable. It's in our backlog and we'll introduce it. Currently, only Cocoapods and Carthage is supported.

**Comment by marcnpopa** [comment]
Cool, thank you for the fast response. I will use Carthage
