### ISSUE TITLE
Old version of Alamofire 

### ISSUE THREAD

**Issue by AndrewRudyk** [GetStream/swift-activity-feed#9]
Hello!
Could you please update version of Alamofire (5.0 or latest).
We use latest version and it conflicts with old version on your side.

**Comment by b-onc** [comment]
Hello @AndrewRudyk 
Can you paste the conflicts here?

**Comment by AndrewRudyk** [comment]
> Hello @AndrewRudyk
> Can you paste the conflicts here?

This a conflict when installing Pods.
I have Alamofire with version  5.2 (pod 'Alamofire', '~> 5.2'), when I'm installing pod 'GetStreamActivityFeed', it has 'Alamofire', '4.1 in .podspec.
Do you need more details?

**Comment by b-onc** [comment]
GetStreamActivityFeed does not directly depend on Alamofire, podspec doesn't have dependency entry. The failure you're getting must be indirect, if you paste the shell output of `pod install` we should spot it.

**Comment by AndrewRudyk** [comment]
> GetStreamActivityFeed does not directly depend on Alamofire, podspec doesn't have dependency entry. The failure you're getting must be indirect, if you paste the shell output of `pod install` we should spot it.

Terminal log when I'm installing pods

[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 5.2.0, ~> 5.2)

  In Podfile:
    Alamofire (~> 5.2)

    GetStreamActivityFeed (~> 1.0) was resolved to 1.0.11, which depends on
      GetStream (~> 1.1) was resolved to 1.1.0, which depends on
        GetStream/Core (= 1.1.0) was resolved to 1.1.0, which depends on
          Moya (~> 12.0) was resolved to 12.0.0, which depends on
            Moya/Core (= 12.0.0) was resolved to 12.0.0, which depends on
              Alamofire (~> 4.1)

depends in Moya/Core

**Comment by b-onc** [comment]
@AndrewRudyk The issue is in GetStream pod, not GetStreamActivityFeed.
There's an open issue in that repo: https://github.com/GetStream/stream-swift/issues/25
And an open PR which should resolve this problem too: https://github.com/GetStream/stream-swift/pull/28
Please try the PR branch, and comment on the issue the result. We will be releasing the new version if it's working as expected.
